### ISSUE TITLE
Connection string functionality missing

### ISSUE THREAD

**Issue by pinn3** [jspizziri/sequelize-connect#13]
In the docs there is an entry about using connection strings instead of separate parameters, but after checking the `lib/Connection.js` I fail to find any sort of functionality for handling it.

The docs also tells us to specify a dialect and port, which seems redundant as a connection string would look something like this `postgres://user@localhost:5432/database`, if I'm not mistaking.

**Comment by jspizziri** [comment]
There isn't any code in the lib that handles the connection string, it's all farmed out to Sequelize.

Effectively, the Sequelize constructor interface is [mirrored](https://github.com/jspizziri/sequelize-connect/blob/master/lib/Connection.js#L51), so anything that Sequelize does, is should be supported by this lib as well.

**Comment by pinn3** [comment]
Oh I see, so the `database` param can either be the database name, but also the connection string I assume?
It's still quite odd as Sequelize can handle the dialect and port from that without us having to pass in an options object.

**Comment by jspizziri** [comment]
It's just an exact copy of the [Sequelize constructor signature](https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L115). The intent is to provide the exact same interface, so you can interact with it exactly as you do sequelize.

If you don't want to use the options object, simply don't pass it in.

**Comment by pinn3** [comment]
Yup, did that and it defaulted to mysql instead of postgres as my connection string intended. This is not the case with the Sequelize package though.

**Comment by jspizziri** [comment]
hmmm, interesting, sounds like a bug. Please submit a PR if you're able! It will probably be a bit before I'm able to get to it.

**Comment by pinn3** [comment]
Aight, will have a deeper look into this!
