### ISSUE TITLE
Closing the connection

### ISSUE THREAD

**Issue by williamgranli** [jspizziri/sequelize-connect#15]
Is there any way to close the connection, i.e. stopping whatever is made with new Connection(). 

Could I do something like
const orm = new Connection();
orm.close();

I want to use it in my after clause when runnings tests. 

Thanks! #

**Comment by jspizziri** [comment]
@williamgranli,

I know this is super late. But a `Connection` instance has a public property of the `seqeulize` instance on it. You should be able to close the connection by doing the following:

```js
var Connection = require('sequelize-connect');
var orm = new Connection();
var sequelize = orm.sequelize;
sequelize.close();
```
