### ISSUE TITLE
db.models is not exposed ?

### ISSUE THREAD

**Issue by laoyur** [jspizziri/sequelize-connect#3]
connect.js line 69:
`// db.models    = models;`

**Comment by jspizziri** [comment]
Fixed: https://github.com/jspizziri/sequelize-connect/commit/cc94da9b5b573221a1cc5b9cc9d96df2a5e4b7e8, please install https://github.com/jspizziri/sequelize-connect/releases/tag/v1.2.1

**Comment by FullPint** [comment]
I seem to be having a similar issue. 

In the docs it says :
> After connecting you can access the sequelize instance and models wherever you need!

So I run :
` var Connection = require('sequelize-connect');
   var orm = new Connection();
   var Admin = orm.models.Admin;
`
And I receive: 
`TypeError: Cannot read property 'Admin' of undefined`

I'm not sure why this would happen if the models are being placed in my DB.
