### ISSUE TITLE
Make It Possible to Assign String to Discover?

### ISSUE THREAD

**Issue by bookercodes** [jspizziri/sequelize-connect#4]
Would you consider accepting a pull request that makes it possible to assign a `String` to `discover`?

``` javascript
// Currently valid:
orm.discover = [__dirname + '/models'];

// Currently invalid:
orm.discover = __dirname + '/models';
// ... I want it to be valid
```

**Justification**

I put all my models in a single `/models` directory. I only need to specify one path (`/models`). I think it would be pleasant to assign a `String` instead of `String[]`.

**Comment by bookercodes** [comment]
@jspizziri, I see you added the **enhancement** label. Does this mean you'd accept a pull request for this?

**Comment by jspizziri** [comment]
Yeah, I see no harm in adding the shortcut for convenience. Go ahead and submit a PR, and I'll merge it in.

**Comment by jspizziri** [comment]
Also, I'd like to start using conventional-changelog on this project, so if you could use that for your commit's that would be great. And if you do, if you would also add [Commitizen](https://www.npmjs.com/package/commitizen) to the package.json, that would be great!

**Comment by jspizziri** [comment]
Released in https://github.com/jspizziri/sequelize-connect/releases/tag/v1.2.2.
