### ISSUE TITLE
Why depend on Winston?

### ISSUE THREAD

**Issue by bookercodes** [jspizziri/sequelize-connect#9]
Hi, @jspizziri :wave: 

I'm just wondering why you chose to tightly couple `sequelize-connect` with Winston? 

This is the first time I've seen this pattern, so I'm curious as to what your thinking is.

Thanks :smile:

**Comment by jspizziri** [comment]
@alexbooker,

A fair point! I think the thinking at the time was `I want to use winston!`, and didn't go much deeper than that. Now that you bring it up however, what I'd like to do is switch to a more standard dependency injection pattern, and likely at the same time rewrite the package in es2015.

**Comment by bookercodes** [comment]
> I'd like to do is switch to a more standard dependency injection pattern

I don't mean to be rude but is logging worth it? I don't **personally** see a need for logging in such a simple module. Automated tests would be a better substitute for `"debug"` logs.

> rewrite the package in es2015.

Nice :+1: 

What are you planning to do, target a newer version of Node or transpile the code using Babel (or [Buble](https://gitlab.com/Rich-Harris/buble) :open_mouth:)?

**Comment by jspizziri** [comment]
This is along the lines of [what I'm thinking](https://github.com/jspizziri/sequelize-connect/tree/2.0.0-refactor).

 **Disclaimer**: I have no idea if this is working, didn't test it at all, just threw some code together.

Also, you're totally right about the `debug` logs, it would be great to remove those in favor of automated tests (hint hint 😉 😉). I still do like the idea of providing some level of logging, link on connection and import complete events, but I'm open to being wrong about that.

Take a look and let me know what you think, I'm totally open to constructive criticism 😄.

**Comment by bookercodes** [comment]
Well, like I say, I don't **personally** have any need for logging but if you find value in it, by all means, keep it. I only care at all because **1,** [I had to figure out how to disable it](https://github.com/jspizziri/sequelize-connect/pull/5) and **2,** [I got bitten by a related issue](https://github.com/jspizziri/sequelize-connect/pull/10). Based on **my** needs and **my** experiences I would like to see it removed or at least, disabled by default.

Your [branch](https://github.com/jspizziri/sequelize-connect/tree/2.0.0-refactor) looks promising. Here is my initial feedback:
- [You should use `module.exports` instead of `export default` for the sake of people still using `require`](https://medium.com/@kentcdodds/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution-ad2d5ab93ce0#.y8ewd1vb5)
- [Consider using npm scripts instead of Gulp](https://medium.freecodecamp.com/why-i-left-gulp-and-grunt-for-npm-scripts-3d6853dd22b8). That's what I do for [`base16-builder`](https://github.com/base16-builder/base16-builder) and it works great :+1:. I also wrote about it [here](https://booker.codes/how-to-build-and-publish-es6-npm-modules-today-with-babel/).
- If you're using Babel you might as well use [`babel-preset-stage-3`](http://babeljs.io/docs/plugins/preset-stage-3/). [Asynchronous functions](https://jakearchibald.com/2014/es7-async-functions/) work a treat with Sequelize ([just look :heart:](https://github.com/alexbooker/communitycasts.co/blob/master/source/models/screencast.js#L40)). 

I can give more specific feedback closer to release if you want?

**Comment by jspizziri** [comment]
Thanks for your initial feedback! I think disabling logging by default is a good idea.
- module.exports sounds like a good idea, I'll implement that.
- NPM scripts sound interesting, I've never actually used them before. I'll dig into them a little more, although I am a huge fan of gulp... 😢
- Since Stage 3 features aren't actually accepted in the official spec I'd prefer to wait (even if it's likely they'll get accepted at that stage anyway).

**Comment by jspizziri** [comment]
[v2.0.0](https://github.com/jspizziri/sequelize-connect/releases/tag/v2.0.0)

**Comment by jspizziri** [comment]
@alexbooker, let me know what you think.

**Comment by bookercodes** [comment]
@jspizziri I'll migrate now and let you know how it goes :wink:

**Comment by bookercodes** [comment]
Seems to just ignore the `discover` argument :cry: 

``` javascript
async function connectToDatabase () {
  const discover = [path.join(__dirname, './models')]
  const matcher = function shouldImportModel (modelFileName) {
    return true
  }
  await new Connection(
    config.database,
    config.username,
    config.password, {
      force: true,
      logging: false
    },
    discover,
    matcher)
}
```

![](http://i.imgur.com/KXZWg6U.png)

**Comment by jspizziri** [comment]
Hmmmm, that's weird, I swore I tested that. Sorry! Let me take a peek at it!

**Comment by jspizziri** [comment]
The only scenario in which it would be trying to scan the directory `/model` is if the `discover` argument is `undefined`. I'm not sure why it would be ignoring your `const`. It's weird because I'm not getting that error.

Do you have the whole stacktrace?

**Comment by bookercodes** [comment]
I know, right :confused:? I peeked at the `Connection` constructor and it doesn't make sense.  

I would expect there to be more but that _is_ the whole stack trace ([`Error.stack`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack)). 

The only other information I have is:

```
Unhandled rejection Error: ENOENT: no such file or directory, scandir '/model'
    at Error (native)
{ [Error: ENOENT: no such file or directory, scandir '/model']
  cause: { [Error: ENOENT: no such file or directory, scandir '/model'] errno: -2, code: 'ENOENT', syscall: 'scandir', path: '/model' },
  isOperational: true,
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/model' }
```

**Comment by jspizziri** [comment]
Gahhhh...

That's frustrating. #NonDeterministicAlgorithm. 

Would you be able to list some steps for me to reproduce the issue with the [project you're using](https://github.com/alexbooker/communitycasts.co)?

**Comment by alexbooker** [comment]
Are you on Google+ or something? I can show you my screen if you have 10 minutes.

**Comment by bookercodes** [comment]
I made a branch `connect-bug`. Try:

```
git clone https://github.com/alexbooker/communitycasts.co
git checkout connect-bug
npm install
npm run start
```

You'll also need to create a `config/development.json` file:

```
{
  "youtubeApiKey": "foo",
  "adminPassword": "foo",
  "database": "communitycasts_schema",
  "username": "root",
  "password": "",
  "screencastsPerPage": 2
}
```

**Comment by alexbooker** [comment]
I am making some progress in debugging this: `discover` is set properly in `Connection` constructor but `['/model']` is still passed to `Discoverable`.

**Comment by jspizziri** [comment]
@alexbooker, what version of node are you running on. I just ran your steps to repro and didn't get it, it must be relative to node.

**Comment by bookercodes** [comment]
@jspizziri Or platform. I'm on Linux, what about you?

I tried with Node 5 and 6

**Comment by jspizziri** [comment]
@alexbooker, nvm, it looks like the connect-bug branch still had the old package installed, installed 2.0.0 and retesting.

**Comment by bookercodes** [comment]
Sorry

**Comment by jspizziri** [comment]
@alexbooker, no worries. I had node 4 installed and it worked, I'm testing with node 5.11.1 now.

**Comment by jspizziri** [comment]
@alexbooker just worked on node 5.11.1. Are we running the same code?

``` js
import Connection from 'sequelize-connect'
import path from 'path'
import app from './app'
import config from 'config'


async function connectToDatabase () {
  const discover = [path.join(__dirname, './models')]
  const matcher = function shouldImportModel (modelFileName) {
    return true
  }
  await new Connection(
    config.database,
    config.username,
    config.password, {
      force: true,
      logging: false
    },
    discover,
    matcher,
    console
  )
}

(async function () {
  await connectToDatabase()
  const port = 3000
  app.listen(port, error => {
    if (error) {
      console.log(`An error occured: ${error}`)
    } else {
      console.log(`Running on port ${port}`)
    }
  })
})()
```

**Comment by jspizziri** [comment]
Also, I'm running on Mac OS X - El Capitan

Here's my debug log:

```
info Connecting to: communitycasts_schema as: Jacob
debug Discovered path: /Users/Jacob/Documents/Projects/communitycasts.co/source/models/channel.js
debug Discovered path: /Users/Jacob/Documents/Projects/communitycasts.co/source/models/screencast.js
debug Discovered path: /Users/Jacob/Documents/Projects/communitycasts.co/source/models/screencastTag.js
debug Discovered path: /Users/Jacob/Documents/Projects/communitycasts.co/source/models/tag.js
debug Flattening results
debug Assigning filtered results to discover: /Users/Jacob/Documents/Projects/communitycasts.co/source/models/channel.js,/Users/Jacob/Documents/Projects/communitycasts.co/source/models/screencast.js,/Users/Jacob/Documents/Projects/communitycasts.co/source/models/screencastTag.js,/Users/Jacob/Documents/Projects/communitycasts.co/source/models/tag.js
debug Import for path succeeded: /Users/Jacob/Documents/Projects/communitycasts.co/source/models/channel.js
debug Import for path succeeded: /Users/Jacob/Documents/Projects/communitycasts.co/source/models/screencast.js
debug Import for path succeeded: /Users/Jacob/Documents/Projects/communitycasts.co/source/models/screencastTag.js
debug Import for path succeeded: /Users/Jacob/Documents/Projects/communitycasts.co/source/models/tag.js
info Import completed
debug Associating Model: channel
debug Associating Model: screencast
debug Nothing to associate for Model: screencastTag
debug Associating Model: tag
info Finished connecting to: communitycasts_schema as: Jacob
info Finished synchronizing communitycasts_schema
Running on port 3000
```

**Comment by bookercodes** [comment]
One moment

**Comment by bookercodes** [comment]
I forgot to `commit` my changes to the `connect-bug` branch :confused:

**Comment by jspizziri** [comment]
Can you commit and push? I'll retest.

**Comment by bookercodes** [comment]
Just did: https://github.com/alexbooker/communitycasts.co/commit/f6bf3dd1e83d2dc5c3d328357c7f1358c365327e

Sorry again.

**Comment by jspizziri** [comment]
bingo, I've got it now. No worries, I couldn't count the times I've forgotten to save a file or commit 😉

**Comment by bookercodes** [comment]
Thanks for understanding.

The code plays a bit nicer with `node debug` when you don't use `async` functions. Here's the equivalent `index.js` file using `Promise`s for your convenience:

``` javascript
import Connection from 'sequelize-connect'
import path from 'path'
import app from './app'
import config from 'config'

function connectToDatabase () {
  const discover = [path.join(__dirname, './models')]
  const matcher = function shouldImportModel (modelFileName) {
    return true
  }
  debugger
  return new Connection(config.database, config.username, config.password, {}, discover, matcher, console)
}

connectToDatabase().then(() => {
  const port = 3000
  app.listen(port, error => {
    if (error) {
      console.log(`An error occured: ${error}`)
    } else {
      console.log(`Running on port ${port}`)
    }
  })
}).catch(err => console.log(err))
```

**Comment by jspizziri** [comment]
So it looks like `new Connection()` in `source/middleware/submitScreencastValidator.js` is being called before the `new Connection(......)` in `index.js`, which is intializing discover as null. Interesting.

**Comment by bookercodes** [comment]
That _is_ interesting because I don't even initialize Express until the promise returned by `Connect` resolves :confused:

**Comment by jspizziri** [comment]
Ahhh

``` js
// index.js

import app from './app'
...
function connectToDatabase () {
  ...
  return new Connection(config.database, config.username, config.password, {}, discover, matcher, console)
}
```

``` js
// app.js
import validateSubmitScreencastReq from './middleware/submitScreencastValidator.js'
```

So submitScreencastValidator.js is being called before initializing the connection.

**Comment by bookercodes** [comment]
That makes perfect sense

**Comment by jspizziri** [comment]
Super messy but this works

``` js
import Connection from 'sequelize-connect'
import path from 'path'
// import app from './app'
import config from 'config'

function connectToDatabase () {
  const discover = [path.join(__dirname, './models')]
  const matcher = function shouldImportModel (modelFileName) {
    return true
  }
  debugger
  return new Connection(config.database, config.username, config.password, {}, discover, matcher, console)
}

connectToDatabase().then(() => {
  const port = 3000

  // this works, because it's loading the middleware after the connection initializes
  var app = require('./app');

  app.listen(port, error => {
    if (error) {
      console.log(`An error occured: ${error}`)
    } else {
      console.log(`Running on port ${port}`)
    }
  })
}).catch(err => console.log(err))

```

**Comment by bookercodes** [comment]
Would you consider abandoning the constructor function?

I'll make a separate issue and state my case.

**Comment by jspizziri** [comment]
@alexbooker, yea state your case. I'll check it out later and we can try to figure something out.
